spring.application.name=core-engine

# Configuração do Banco em Memória H2
spring.datasource.url=jdbc:h2:mem:erpdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Faz o Hibernate criar/atualizar as tabelas automaticamente na inicialização
spring.jpa.hibernate.ddl-auto=update

# Ativa o console visual do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Libera visualização de frames para o H2 Console
spring.h2.console.settings.web-allow-others=true